### Register User
POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "Zen",
    "email": "zen@gmail.com",
    "password": "adminadmin1",
    "passwordConfirmation": "adminadmin1"
}


### Login
POST http://localhost:8800/api/auth/login
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "adminadmin1"
}


### Update User
PATCH http://localhost:8800/api/user/62a449522071a304f6f5e395
Content-Type: application/json

{
    "username": "merry",
    "userId": "62a449522071a304f6f5e395",
    "city": "New York",
    "from": "US",
    "relationship": "Single"
}

### Delete User 
DELETE http://localhost:8800/api/user/62a4890caec36ce4ff44a487
Content-Type: application/json

{
    "userId": "62a4890caec36ce4ff44a487"
}

### Get User by id
GET http://localhost:8800/api/user/by-query?userId=62a449522071a304f6f5e395

### Get User by username
GET http://localhost:8800/api/user/by-query?username=merry


### Follow User
PATCH  http://localhost:8800/api/user/follow/62a47947a9b0fe7afdda65bd
Content-Type: application/json

{
    "userId": "62a449522071a304f6f5e395"
}

### UnFollow User
PATCH  http://localhost:8800/api/user/unfollow/62a4890caec36ce4ff44a487
Content-Type: application/json

{
    "userId": "62a4890caec36ce4ff44a487"
}


### Get User's Friends
GET http://localhost:8800/api/user/friends/62a449522071a304f6f5e395